import compression from "compression";
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import morgan from "morgan";
import { env } from "./config/env.js";
import projectRoutes from "./routes/project.routes.js";
import skillRoutes from "./routes/skill.routes.js";
import serviceRoutes from "./routes/service.routes.js";
import experienceRoutes from "./routes/experience.routes.js";
import testimonialRoutes from "./routes/testimonial.routes.js";
import siteSettingsRoutes from "./routes/siteSettings.routes.js";
import contactRoutes from "./routes/contact.routes.js";
import { notFound } from "./middleware/notFound.js";
import { errorHandler } from "./middleware/errorHandler.js";
const app = express();
app.use(cors({ origin: [env.clientUrl, "http://localhost:5173"], credentials: true }));
app.use(helmet());
app.use(compression());
app.use(morgan("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 300, standardHeaders: true, legacyHeaders: false }));
app.get("/", (req, res) => res.json({ success: true, message: "API is running" }));
app.get("/api/health", (req, res) => res.json({ success: true, message: "API is running" }));
app.use("/api/projects", projectRoutes);
app.use("/api/skills", skillRoutes);
app.use("/api/services", serviceRoutes);
app.use("/api/experiences", experienceRoutes);
app.use("/api/testimonials", testimonialRoutes);
app.use("/api/site-settings", siteSettingsRoutes);
app.use("/api/contact", contactRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
